#!/bin/bash
function n_options() {
  echo "n <subcommand>"
  echo "<subcommand> may be 'log', 'options'"
}

function n() {
  if [ $# -lt 1 ]
  then
    n_options
  fi
  case $1 in
    "log" )
      watch -n 5 "nova console-log --length=40 $2";;
    "list" )
      nova list;;
    "options" )
      n_options;;
    * )
      nova "$@"
  esac
}
